Create Database db_LibrariesDavid

USE db_LibrariesDavid
GO

CREATE TABLE PUBLISHERS (
	[Name] varchar(50) PRIMARY KEY NOT NULL,
	[Address] varchar(50) NOT NULL,
	Phone INT NOT NULL
)

CREATE TABLE BORROWERS (
	CardNo INT PRIMARY KEY NOT NULL IDENTITY (1000, 10),
	NameBorrower varchar(50) NOT NULL,
	[Address] varchar(50) NOT NULL,
	Phone INT NOT NULL
)

CREATE TABLE LIBRARY_BRANCH (
	BranchID INT PRIMARY KEY NOT NULL IDENTITY (300, 1),
	BranchName varchar(50) NOT NULL,
	[Address] varchar(500) NOT NULL
)

CREATE TABLE BOOK (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (2000,10),
	Title varchar(50) NOT NULL,
	PublisherName varchar(50) CONSTRAINT fk_publishername_id FOREIGN KEY(PublisherName) REFERENCES PUBLISHERS([Name]) ON UPDATE CASCADE ON DELETE CASCADE
)


CREATE TABLE BOOK_AUTHORS (
	BookID INT CONSTRAINT fk_Book_id FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName varchar(50) NOT NULL
)

CREATE TABLE BOOK_LOANS (
	BookID INT CONSTRAINT fk_Book2_id FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT CONSTRAINT fk_Branch_id FOREIGN KEY (BranchID) REFERENCES LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo INT CONSTRAINT fk_Borrower_id FOREIGN KEY (CardNo) REFERENCES BORROWERS(CardNo) ON UPDATE CASCADE ON DELETE CASCADE, 
	DateOut DATE NOT NULL,
	DueDate DATE NOT NULL
)

CREATE TABLE BOOK_COPIES (
	BookID INT CONSTRAINT fk_Book3_id FOREIGN KEY (BookID) REFERENCES BOOK(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT CONSTRAINT fk_Branch2_id FOREIGN KEY (BranchID) REFERENCES LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	No_Of_Copies INT NOT NULL
)

